language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
env:
  - DJANGO=1.4.4
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=1.5.1
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.4
    - python: "3.3"
      env: DJANGO=1.4.5
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q django-nose==1.2 --use-mirrors
  - pip install -e . --use-mirrors
script:
  - python runtests.py
